In [1]:
import pandas as pd
import numpy as np

Load the Data

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of Week  \
0         0         0         0         1            7            1   
1         0         0         0         0            7            1   
2         0         0         0         1            7            2   
3         1         0         0         0            7            3   
4         0         0         0         1            7            3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0               30          0         2    1                          4  
1               31          0         1    0                          0  
2               31          0         0    0                          2  
3               24          0         2    0                          4  
4               30          0         2    1                          2

Determine excessive amount of absenteeism

In [3]:
median = data_preprocessed['Absenteeism Time in Hours'].median()
print(f'Median absent time is {median} hours')
targets = np.where(data_preprocessed['Absenteeism Time in Hours']>median,1,0)
targets

Median absent time is 3.0 hours


array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [4]:
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of Week  \
0         0         0         0         1            7            1   
1         0         0         0         0            7            1   
2         0         0         0         1            7            2   
3         1         0         0         0            7            3   
4         0         0         0         1            7            3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0               30          0         2    1                          4   
1               31          0         1    0                          0   
2               31          0         0    0                          2   
3               24          0         2    0                          4   
4               30          0         2    1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [5]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [6]:
data_with_targets = data_preprocessed.drop('Absenteeism Time in Hours', axis=1)
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of Week  \
0         0         0         0         1            7            1   
1         0         0         0         0            7            1   
2         0         0         0         1            7            2   
3         1         0         0         0            7            3   
4         0         0         0         1            7            3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Excessive Absenteeism  
0               30          0         2    1                      1  
1               31          0         1    0                      0  
2               31          0         0    0                      0  
3               24          0         2    0                      1  
4               30          0         2    1                      0

Select inputs

In [7]:
unscaled_inputs = data_with_targets.iloc[:,:-1]
unscaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of Week  \
0           0         0         0         1            7            1   
1           0         0         0         0            7            1   
2           0         0         0         1            7            2   
3           1         0         0         0            7            3   
4           0         0         0         1            7            3   
..        ...       ...       ...       ...          ...          ...   
695         1         0         0         0            5            2   
696         1         0         0         0            5            2   
697         1         0         0         0            5            3   
698         0         0         0         1            5            3   
699         0         0         0         1            5            3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pet  
0                 30          0         2    1  
1                 31          0         1    0  
2                 31          0         0    0  
3                 24          0         2    0  
4                 30          0         2    1  
..               ...        ...       ...  ...  
695               22          1         2    0  
696               24          0         1    2  
697               25          1         0    0  
698               25          1         0    0  
699               25          0         1    1  

[700 rows x 14 columns]

Scale the data

In [8]:
from sklearn.preprocessing import StandardScaler
absenteeism_scaler = StandardScaler()
unscaled_inputs = unscaled_inputs.drop(['Daily Work Load Average', 'Day of Week', 'Distance to Work'], axis=1)
absenteeism_scaler.fit(unscaled_inputs)
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size=.8, random_state=20)

Logistic regression with sklearn

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics


In [11]:
reg = LogisticRegression()
reg.fit(X_train, y_train)

LogisticRegression()

In [12]:
reg.score(X_train, y_train)

0.7839285714285714

Manually check accuracy

In [13]:
model_outputs = reg.predict(X_train)

In [14]:
misclassifications = sum(abs(model_outputs-y_train))
samples = len(X_train)
print(misclassifications)
print((samples-misclassifications)/samples)

121
0.7839285714285714


Intercept and coefficients

In [15]:
feature_names = unscaled_inputs.columns.values
summary_table = pd.DataFrame(columns=['Feature Name'], data = feature_names)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature Name  Coefficient
0                 Reason_1     2.069521
1                 Reason_2     0.335811
2                 Reason_3     1.562039
3                 Reason_4     1.312780
4              Month Value     0.184698
5   Transportation Expense     0.691262
6                      Age    -0.198283
7          Body Mass Index     0.324360
8                Education    -0.126656
9                 Children     0.370177
10                     Pet    -0.325359

In [16]:
summary_table.index = summary_table.index+1
summary_table.loc[0] = ['Intercept', reg.intercept_.item()]
summary_table = summary_table.sort_index()
summary_table

Feature Name  Coefficient
0                Intercept    -0.223756
1                 Reason_1     2.069521
2                 Reason_2     0.335811
3                 Reason_3     1.562039
4                 Reason_4     1.312780
5              Month Value     0.184698
6   Transportation Expense     0.691262
7                      Age    -0.198283
8          Body Mass Index     0.324360
9                Education    -0.126656
10                Children     0.370177
11                     Pet    -0.325359

Reason 1- Various diseases
Reason 2- Maternity
Reason 3- Poisoning
Reason 4- Light diseases

In [17]:
summary_table.sort_values('Coefficient', ascending=False)

Feature Name  Coefficient
1                 Reason_1     2.069521
3                 Reason_3     1.562039
4                 Reason_4     1.312780
6   Transportation Expense     0.691262
10                Children     0.370177
2                 Reason_2     0.335811
8          Body Mass Index     0.324360
5              Month Value     0.184698
9                Education    -0.126656
7                      Age    -0.198283
0                Intercept    -0.223756
11                     Pet    -0.325359

Test model

In [18]:
reg.score(X_test, y_test)

0.7357142857142858

In [19]:
predicted_proba = reg.predict_proba(X_test)
predicted_proba[:,1]

array([0.29195371, 0.42821649, 0.60104701, 0.21285889, 0.93308484,
       0.68890716, 0.71417622, 0.91906014, 0.20073207, 0.2503313 ,
       0.53227695, 0.81550318, 0.95913368, 0.24403322, 0.76290685,
       0.45859202, 0.46645613, 0.47960025, 0.59492531, 0.97240413,
       0.29851164, 0.21285889, 0.59454382, 0.59454382, 0.82608333,
       0.24637125, 0.51182767, 0.11946745, 0.86940765, 0.21285889,
       0.37752575, 0.69562155, 0.71104836, 0.55842034, 0.21285889,
       0.56294675, 0.20932611, 0.81013019, 0.41289739, 0.63001412,
       0.20415726, 0.42151589, 0.22731649, 0.10486653, 0.85723233,
       0.65470153, 0.70629762, 0.29195371, 0.21207006, 0.19572289,
       0.56549874, 0.07774102, 0.68890716, 0.26970997, 0.85980383,
       0.45421224, 0.93050906, 0.21788125, 0.08531744, 0.08952364,
       0.70559435, 0.6774947 , 0.28721976, 0.86078009, 0.18989327,
       0.27063956, 0.01404469, 0.20932611, 0.81292865, 0.28500657,
       0.20932611, 0.06875653, 0.92859838, 0.47793046, 0.63865

Save model

In [20]:
import pickle
with open('model', 'wb') as file:
    pickle.dump(reg, file)
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)